# Generated by Django 5.2.8 on 2026-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbotuser',
            name='botID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
