services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn stockbot_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.7
