services:
  - type: web
    name: django-api
    runtime: python
    rootDir: backend       
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn stockbot_backend.wsgi:application

  - type: cron
    name: daily-expiry-check
    runtime: python
    rootDir: backend        
    buildCommand: pip install -r requirements.txt
    schedule: "0 8 * * *"
    startCommand: python manage.py check_expiring_items