# Generated by Django 5.2.8 on 2026-01-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sensoringestionevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoringestionevent',
            name='resolved',
        ),
    ]
