# Generated by Django 5.2.8 on 2026-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_sensoringestionevent_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoringestionevent',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensoringestionevent',
            name='image_id',
            field=models.CharField(max_length=128),
        ),
    ]
