# Generated by Django 5.2.8 on 2026-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sensoringestionevent_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_grams',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='initial_grams',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensoringestionevent',
            name='weight_grams',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
