# Generated by Django 5.2.8 on 2026-03-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_current_grams_alter_item_initial_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('in_fridge', 'In Fridge'), ('removed', 'Removed')], default='in_fridge', max_length=20),
        ),
    ]
