# Generated by Django 5.2.8 on 2026-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_last_removed_at_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notified_expiring_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='notified_expiry_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='notified_low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
