# Generated by Django 5.2.8 on 2026-03-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_image_alter_sensoringestionevent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoringestionevent',
            name='image',
        ),
    ]
