# Generated by Django 5.2.8 on 2026-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_sensoringestionevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoringestionevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
